spring:
  application:
    name: AppTesting
  datasource:
    url: jdbc:postgresql://dpg-co0b03fsc6pc738qr69g-a.frankfurt-postgres.render.com:5432/shop_testing_yzu1
    username: shop_testing_yzu1_user
    password: gevJURknoE9pQsXamLuLkBJ93j5P3GyP
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
