spring:
  application:
    name: AppTesting
  datasource:
    url: jdbc:postgresql://dpg-cp756o0l6cac73878gc0-a.frankfurt-postgres.render.com:5432/shop_posting
    username: shop_posting_user
    password: QnJS0qxDO4CY7EWbJ7NzsC6KyzZGA36i
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
management:
  endpoints:
    web:
      exposure:
        include: "*"